server:
  port: 9090
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore/ssafy.p12
#    key-store-password: 123456
#    key-alias: ssafy
#    trust-store: classpath:keystore/ssafy.ts
#    trust-store-password: 123456

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/asap?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: ssafy
      password: root

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

#      ddl-auto: create-drop
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    web:
      pageable:
        one-indexed-parameters: true

  web:
    resources:
      static-locations: classpath:/dist

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://i6b103.p.ssafy.io:3306/asap?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: ssafy
      password: root

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

      #      ddl-auto: create-drop
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    web:
      pageable:
        one-indexed-parameters: true

  web:
    resources:
      static-locations: classpath:/dist

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/asap?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: ssafy
      password: root

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

      #      ddl-auto: create-drop
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    web:
      pageable:
        one-indexed-parameters: true

  web:
    resources:
      static-locations: classpath:/dist